# -*- coding: utf-8 -*-
"""gpt4all_test (runs - no xterm needed).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ibx4NuHqr4JIIeLeIjhVKcvmRWK5WYGq
"""

# https://www.youtube.com/watch?v=vbUhbM7lZO0
!nvidia-smi

!git clone https://github.com/nomic-ai/nomic.git
!git checkout bd9c042

# Commented out IPython magic to ensure Python compatibility.
# %cd nomic

!gdown 1SHhs_AQVV1Ds0wjZ6LfI_T7qdg35k7gZ

!cp gpt4all.py nomic/gpt4all/

!pip install .[GPT4All]

from nomic.gpt4all.gpt4all import GPT4AllGPU
import textwrap

m = GPT4AllGPU("decapoda-research/llama-7b-hf")

config = {
  'num_beams': 2,
  # 'min_new_tokens': 10,
  'max_new_tokens': 1000,
  # 'max_length': 200,
  'repetition_penalty': 2.0
}
import re
def print_response(prompt: str) -> str:
    raw_response = m.generate(prompt, config)
    raw_response = "\n".join(textwrap.wrap(raw_response))
    print('--> RAW RESPONSE: \n\n')
    print(raw_response)
    first_sentence = raw_response
    search_for_first_sentence = re.findall(r'(^.+?(\.|\?|!|$))', raw_response)
    if (len(search_for_first_sentence) > 0 and len(search_for_first_sentence[0]) > 0):
      first_sentence = re.findall(r'(^.+?(\.|\?|!|$))', raw_response)[0][0]
    print('\n--> FIRST SENTENCE: \n\n')
    print(first_sentence)

print_response("""Question: What colour is a crazy carrot?

You will provide one answer to this one question. Info to base your answer on:

###START OF INFO###
- Accordion apples are red.
- Bass bananas are yellow.
- An accordion apple is red.
- Crazy carrots are blue.
###END OF INFO###

Answer based on the info above: """)

print_response("""
# Templates:

## dropdown template:
```html
<select class="custom-control">
  <option value="">- Please select -</option>
  <option value="1">1</option>
  <option value="2">2</option>
  ...
</select>
```

## radio template:
```html
<input class="custom-control" type="radio"/>
```

# Task:
Use just one of the templates above to write HTML code for a dropdown of the Canadian provinces:
""")