# -*- coding: utf-8 -*-
"""gpt4all_groovy.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Y-ZptCbXO4KZBM-7O2d-6K-NXYioLRsH
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# !pip install gpt4all
# import gpt4all
# model = gpt4all.GPT4All("ggml-gpt4all-j-v1.3-groovy.bin")
# # model.chat_completion() doc: https://docs.gpt4all.io/gpt4all_python.html#gpt4all.gpt4all.GPT4All.chat_completion
# # other documentation: https://github.com/nomic-ai/gpt4all/blob/main/gpt4all-bindings/python/docs/gpt4all_python.md

def print_response(prompt: str) -> str:
  messages = [{'role': 'user', 'content': prompt}]
  response = model.chat_completion(messages)
  print(response)
  # print(response.get('choices',[{'message':{'content':''}}])[0]['message']['content'])

print_response("""
Question: What colour is a crazy carrot?

You will provide one answer to this one question. Info to base your answer on:

###START OF INFO###
- Accordion apples are red.
- Bass bananas are yellow.
- An accordion apple is red.
- Crazy carrots are blue.
###END OF INFO###

Answer based on the info above:
""")

print_response("""
# Templates:

## dropdown template:
```html
<select class="custom-control">
  <option value="">- Please select -</option>
  <option value="1">1</option>
  <option value="2">2</option>
  ...
</select>
```

## radio template:
```html
<input class="custom-control" type="radio"/>
```

# Task:
Use just one of the templates above to write vanilla HTML code for a dropdown of the Canadian provinces:
""")